# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imdb.proto',
  package='tutorial',
  serialized_pb=_b('\n\nimdb.proto\x12\x08tutorial\"\x92\x04\n\x05Movie\x12\x0c\n\x04name\x18\x01 \x02(\t\x12!\n\x03\x64or\x18\x02 \x02(\x0b\x32\x14.tutorial.Movie.Date\x12$\n\x05genre\x18\x03 \x01(\x0e\x32\x15.tutorial.Movie.Genre\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\r\n\x05\x61\x63tor\x18\x05 \x03(\t\x12\x10\n\x08\x64irector\x18\x06 \x03(\t\x12&\n\x06review\x18\x07 \x03(\x0b\x32\x16.tutorial.Movie.Review\x1aG\n\x04\x44\x61te\x12\x0b\n\x03\x64\x61y\x18\x01 \x02(\x05\x12$\n\x05month\x18\x02 \x02(\x0e\x32\x15.tutorial.Movie.Month\x12\x0c\n\x04year\x18\x03 \x02(\x05\x1a^\n\x06Review\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x05\x12!\n\x03\x64oc\x18\x03 \x01(\x0b\x32\x14.tutorial.Movie.Date\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\"s\n\x05Month\x12\x07\n\x03Jan\x10\x00\x12\x07\n\x03\x46\x65\x62\x10\x01\x12\x07\n\x03Mar\x10\x02\x12\x07\n\x03\x41pr\x10\x03\x12\x07\n\x03May\x10\x04\x12\x07\n\x03Jun\x10\x05\x12\x07\n\x03Jul\x10\x06\x12\x07\n\x03\x41ug\x10\x07\x12\x07\n\x03Sep\x10\x08\x12\x07\n\x03Oct\x10\t\x12\x07\n\x03Nov\x10\n\x12\x07\n\x03\x44\x65\x63\x10\x0b\"9\n\x05Genre\x12\r\n\tAdventure\x10\x00\x12\n\n\x06Sci_fi\x10\x01\x12\n\n\x06\x43omedy\x10\x02\x12\t\n\x05\x44rama\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MOVIE_MONTH = _descriptor.EnumDescriptor(
  name='Month',
  full_name='tutorial.Movie.Month',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Jan', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Feb', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mar', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Apr', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='May', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jun', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jul', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Aug', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sep', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Oct', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Nov', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Dec', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=381,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_MONTH)

_MOVIE_GENRE = _descriptor.EnumDescriptor(
  name='Genre',
  full_name='tutorial.Movie.Genre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Adventure', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sci_fi', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Comedy', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Drama', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=498,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_GENRE)


_MOVIE_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='tutorial.Movie.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='tutorial.Movie.Date.day', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month', full_name='tutorial.Movie.Date.month', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year', full_name='tutorial.Movie.Date.year', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=283,
)

_MOVIE_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='tutorial.Movie.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='tutorial.Movie.Review.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='tutorial.Movie.Review.rating', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc', full_name='tutorial.Movie.Review.doc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='tutorial.Movie.Review.comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=379,
)

_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='tutorial.Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.Movie.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dor', full_name='tutorial.Movie.dor', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genre', full_name='tutorial.Movie.genre', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='tutorial.Movie.duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actor', full_name='tutorial.Movie.actor', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='director', full_name='tutorial.Movie.director', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='review', full_name='tutorial.Movie.review', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MOVIE_DATE, _MOVIE_REVIEW, ],
  enum_types=[
    _MOVIE_MONTH,
    _MOVIE_GENRE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=555,
)

_MOVIE_DATE.fields_by_name['month'].enum_type = _MOVIE_MONTH
_MOVIE_DATE.containing_type = _MOVIE
_MOVIE_REVIEW.fields_by_name['doc'].message_type = _MOVIE_DATE
_MOVIE_REVIEW.containing_type = _MOVIE
_MOVIE.fields_by_name['dor'].message_type = _MOVIE_DATE
_MOVIE.fields_by_name['genre'].enum_type = _MOVIE_GENRE
_MOVIE.fields_by_name['review'].message_type = _MOVIE_REVIEW
_MOVIE_MONTH.containing_type = _MOVIE
_MOVIE_GENRE.containing_type = _MOVIE
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(

  Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
    DESCRIPTOR = _MOVIE_DATE,
    __module__ = 'imdb_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Movie.Date)
    ))
  ,

  Review = _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), dict(
    DESCRIPTOR = _MOVIE_REVIEW,
    __module__ = 'imdb_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Movie.Review)
    ))
  ,
  DESCRIPTOR = _MOVIE,
  __module__ = 'imdb_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Movie)
  ))
_sym_db.RegisterMessage(Movie)
_sym_db.RegisterMessage(Movie.Date)
_sym_db.RegisterMessage(Movie.Review)


# @@protoc_insertion_point(module_scope)
